alert("Hello World")
console.log("code is running")
console.log("code is also running")
console.log("code is looking like a wow ")
var a = prompt("Enter your number")
console.log("Your number is " + a)